name: peergram
description: A peer to peer chat app using TCP
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.6.0
  network_info_plus: ^3.0.5
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true