// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmAas6nGAp4muUlLwvQ6d-pGdl0UA3M1w',
    appId: '1:698387044105:android:f06eb73397cbaa346a25d8',
    messagingSenderId: '698387044105',
    projectId: 'chat-application-885bd',
    databaseURL: 'https://chat-application-885bd-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-885bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY77y5bb82LMAjmxK4ZqqXK_ss-W7Ypjo',
    appId: '1:698387044105:ios:e59224b0421c218e6a25d8',
    messagingSenderId: '698387044105',
    projectId: 'chat-application-885bd',
    databaseURL: 'https://chat-application-885bd-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-885bd.appspot.com',
    androidClientId: '698387044105-499t5nh46tu64k5at04t3nomjvmo96o3.apps.googleusercontent.com',
    iosClientId: '698387044105-bq8lhqdpv3atgn9q5iapif6v98optlbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.peergram',
  );
}
